---
# Configure a chain node
- hosts: node
  roles:
    - {role: user, become: true }
    - {role: server, become: true}
    - {role: node, become_user: "{{ node_user }}", become: true, become_method: sudo }
    - {role: services, become: true }
