---
- name: Create a new user
  ansible.builtin.user:
    name: "{{ node_user }}"
    password: "{{ 'password' | password_hash('sha512', 'mysecretsalt') }}"
    groups: adm
    append: true
    state: present
    shell: /bin/bash
    system: true
    create_home: true
    home: "/home/{{ node_user }}"
