---
chain_repo_dir: "{{ node_user_home }}/chain-repo"
chain_bin: "{{ node_user_home }}/go/bin/{{ chain_binary_name }}"
chain_moniker: "{{ node_user }}_node"
validator_moniker: "{{ node_user }}_vali"
# default configuration
cosmovisor_version: v1.0.0
cosmovisor_repository: github.com/cosmos/cosmos-sdk/cosmovisor/cmd/cosmovisor
cosmovisor_bin: "{{ node_user_home }}/go/bin/cosmovisor"
cosmovisor_home: "{{ chain_home }}/cosmovisor"

node_user_home: "/home/{{ node_user }}"
chain_home: "{{ node_user_home }}/{{ chain_folder_name }}"
# app.toml
minimum_gas_prices: '0.0025{{ chain_denom }}'
pruning: default
pruning_keep_recent: '0'
pruning_keep_every: '0'
pruning_interval: '0'
halt_height: '0'
halt_time: '0'
min_retain_blocks: '0'
inter_block_cache: true
index_events: []
iavl_cache_size: '781250'
iavl_disable_fastnode: true
## app.toml: Telemetry Configuration
telemetry_service_name: ''
telemetry_enabled: false
telemetry_enable_hostname: false
telemetry_enable_hostname_label: false
telemetry_enable_service_label: false
prometheus_retention_time: '0'
telemetry_global_labels: []
## app.toml: API Configuration
api_enabled: false
api_swagger: false
api_port: '1317'
api_address: tcp://0.0.0.0:{{ api_port }}
api_max_open_connections: 1000
api_rpc_read_timeout: 10
api_rpc_write_timeout: 0
api_rpc_max_body_bytes: 1000000
api_enabled_unsafe_cors: false
# rosetta
rosetta_enable: false
rosetta_address: ":8080"
rosetta_blockchain: "app"
rosetta_network: "network"
rosetta_retries: 3
rosetta_offline: false
## app.toml: gRPC Configuration
grpc_enabled: true
grpc_port: 9090
## app.toml: gRPC Web Configuration
grpc_web_enabled: true
grpc_web_port: 9091
grpc_web_enable_unsafe_cors: false
grpc_address: 0.0.0.0:{{ grpc_web_prot }}
## app.toml: State Sync Configuration
statesync_snapshot_interval: 0
statesync_snapshot_keep_recent: 2

## Config.toml
config_proxy_app: 'tcp://127.0.0.1:26658'
moniker: "{{ node_user }}_node"
fast_sync: true
db_backend: "goleveldb"
db_dir: "data"
log_level: "info"
log_format: "plain"

config_genesis_file: "config/genesis.json"
config_priv_validator_key_file: "config/priv_validator_key.json"
config_priv_validator_state_file: "data/priv_validator_state.json"
config_priv_validator_laddr: ""
config_node_key_file: "config/node_key.json"
abci: "socket"
filter_peers: false
rpc_port: 26657
rpc_laddr: "tcp://0.0.0.0:{{ rpc_port }}"
rpc_cors_allowed_origins: []
rpc_cors_allowed_methods: ["HEAD", "GET", "POST"]
rpc_cors_allowed_headers: ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time"]
grpc_laddr: ""
grpc_max_open_connections: 900
rpc_unsafe: false
rpc_max_open_connections: 900
rpc_max_subscription_clients: 100
rpc_max_subscriptions_per_client: 5
rpc_experimental_subscription_buffer_size: 200
rpc_experimental_websocket_write_buffer_size: 200
rpc_experimental_close_on_slow_client: false
rpc_timeout_broadcast_tx_commit: "10s"
rpc_max_body_bytes: 1000000
rpc_max_header_bytes: 1048576
rpc_tls_cert_file: ""
rpc_tls_key_file: ""
rpc_pprof_laddr: "localhost:6060"
# p2p configurataion
p2p_port: 26656
p2p_laddr: "tcp://0.0.0.0:{{ p2p_port }}"
p2p_external_address: ""
p2p_seeds: ""
p2p_persistent_peers: "5dc187550a021298f88c3e5905c7dbdd790ff040@167.99.177.244:26656"
p2p_upnp: false
p2p_addr_book_file: "config/addrbook.json"
p2p_addr_book_strict: false
p2p_max_num_inbound_peers: 40
p2p_max_num_outbound_peers: 10
p2p_unconditional_peer_ids: ""
p2p_persistent_peers_max_dial_period: "0s"
p2p_flush_throttle_timeout: "100ms"
p2p_max_packet_msg_payload_size: 1024
p2p_send_rate: 5120000
p2p_recv_rate: 5120000
p2p_pex: true
p2p_seed_mode: false
p2p_private_peer_ids: ""
p2p_allow_duplicate_ip: false
p2p_handshake_timeout: "20s"
p2p_dial_timeout: "3s"
# mempool configurations
mempool_version: "v0"
mempool_recheck: true
mempool_broadcast: true
mempool_wal_dir: ""
mempool_size: 5000
mempool_max_txs_bytes: 1073741824
mempool_cache_size: 10000
mempool_keep_invalid_txs_in_cache: false
mempool_max_tx_bytes: 1048576
mempool_max_batch_bytes: 0
mempool_ttl_duration: "0s"
mempool_ttl_num_blocks: 0
# statesync configuration
statesync_enabled: false
statesync_rpc_servers: ""
statesync_trust_height: 0
statesync_trust_hash: ""
statesync_trust_period: "168h0m0s"
statesync_discovery_time: "15s"
statesync_temp_dir: ""
statesync_chunk_request_timeout: "10s"
statesync_chunk_fetchers: "4"
# fast sync
fastsync_version: "v0"
# consensus
consensus_wal_file: "data/cs.wal/wal"
consensus_timeout_propose: "3s"
consensus_timeout_propose_delta: "500ms"
consensus_timeout_prevote: "1s"
consensus_timeout_commit: "5s"
consensus_timeout_prevote_delta: "500ms"
consensus_timeout_precommit: "1s"
consensus_timeout_precommit_delta: "500ms"
consensus_double_sign_check_height: 0
consensus_skip_timeout_commit: false
consensus_create_empty_blocks: true
consensus_create_empty_blocks_interval: "0s"
consensus_peer_gossip_sleep_duration: "100ms"
consensus_peer_query_maj23_sleep_duration: "2s"
# storage
storage_discrad_abci_responses: false
# indexer
config_indexer: "kv"
psql_conn: ""
# instrumentation
prometheus_enabled: true
prometheus_listen_addr: ":26660"
instrumentation_max_open_connnections: 3
instrumentation_namespace: "tendermint"
# client.toml
client_chain_id: "oasis-2"
client_keyring_backend: "test"
client_output_format: "text"
client_rpc_interface: "tcp://localhost:{{ rpc_port }}"
client_broadcast_mode: "sync"
