---
- name: Set timezone to Asia/jerusalem
  community.general.timezone:
    name: Asia/Jerusalem

- name: Install system required packages
  ansible.legacy.package:
    name:
      - python3
      - python3-pip
      - jq
      - wget
      - git
      - curl
      - gcc
      - findutils
      - make
      - rsync
      - tar
    state: present

# TODO: move this to the user, does'nt need to be with root
- name: Set up pip dependencies
  ansible.builtin.pip:
    name:
      - toml
      - github.py

# TODO: check if works
- name: Set selinux to permissive
  ansible.posix.selinux:
    policy: targeted
    state: permissive
