---
- name: Install system required packages
  ansible.builtin.package:
    name:
      - acl
      - python3
      - wget
      - git
      - curl
      - gcc
      - findutils
      - make
      - rsync
      - tar
    state: present

- name: Upgrade the system
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
  register: apt_cache
  retries: 50

  until: apt_cache is success
# TODO: move this to the user, does'nt need to be with root
- name: Install jq on Ubuntu
  ansible.builtin.apt:
    pkg:
      - jq
