---
- name: Stop existing chain systemd service
  # Check for both `SERVICE_NAME` and `SERVICE_NAME.service`
  when: >
    not use_cosmovisor and (
    (node_service_name in ansible_facts.services) or
    ((node_service_name + '.service') in ansible_facts.services))
  ansible.builtin.systemd:
    state: stopped
    name: "{{ node_service_name }}"
  become_user: root
  become: true
  tags:
    - chain_stop
    - chain_restart

- name: Stop existing cosmovisor systemd service
  when: >
    use_cosmovisor and (
    (cosmovisor_service_name in ansible_facts.services) or
    ((cosmovisor_service_name + '.service') in ansible_facts.services))
  ansible.builtin.systemd:
    state: stopped
    name: "{{ cosmovisor_service_name }}"
  become_user: root
  become: true
  tags:
    - chain_stop
    - chain_restart

- name: Prepare go folder
  ansible.builtin.file:
    path: "{{ node_user_home }}/go/bin"
    state: directory
    recurse: true
    owner: "{{ node_user }}"
    group: "{{ node_user }}"

# Chain installation
- name: Clone chain repo
  ansible.builtin.git:
    repo: "{{ chain_repository }}"
    dest: "{{ chain_repo_dir }}"
    version: "{{ chain_version }}"

- name: Install chain
  ansible.builtin.shell: |
    PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
    make install
  args:
    chdir: "{{ chain_repo_dir }}"
  ignore_errors: true

- name: Check if chain home folder exists
  ansible.builtin.stat:
    path: "{{ chain_home }}"
  register: chain_home_exists

- name: Init chain
  when: not chain_home_exists.stat.exists
  ansible.builtin.shell: |
    cd $HOME
    {{ chain_bin }} init {{ chain_moniker }} --home {{ chain_home }} --chain-id {{ chain_id }}

- name: Add chain bin from go/bin to .bashrc PATH
  when: not use_cosmovisor
  ansible.builtin.blockinfile:
    dest: '{{ node_user_home }}/.bashrc'
    block: |
      export PATH="$PATH:{{ node_user_home }}/go/bin"
    marker: '# {mark} ANSIBLE MANAGED BLOCK - CHAIN PATH'
    insertbefore: EOF
    create: true

# cosmovisor
- name: Check cosmovisor version
  ansible.builtin.shell: |
    PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
    export DAEMON_HOME={{ chain_home }}
    export DAEMON_NAME={{ chain_binary_name }}
    cosmovisor version
  register: cosmovisor_current
  ignore_errors: true

- name: Debug output
  ansible.builtin.debug:
    var: cosmovisor_current

- name: Clone and install cosmovisor
  when: not cosmovisor_version in cosmovisor_current.stdout
  ansible.builtin.shell: |
    PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
    go install cosmossdk.io/tools/cosmovisor/cmd/cosmovisor@latest

- name: Add cosmovisor parmeters to .bashrc file for easy usage
  ansible.builtin.blockinfile:
    dest: "{{ node_user_home }}/.bashrc"
    block: |
      export DAEMON_NAME={{ chain_binary_name }}
      export DAEMON_HOME={{ chain_home }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK - COSMOVISOR CONFIG VAR"
    insertbefore: EOF
    create: true

- name: Init cosmovisor folders
  ansible.builtin.shell: |
    export DAEMON_NAME={{ chain_binary_name }}
    export DAEMON_HOME={{ chain_home }}
    PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
    $HOME/go/bin/cosmovisor init $HOME/go/bin/{{ chain_binary_name }}

- name: Add chain bin from cosmovisor to .bashrc PATH
  ansible.builtin.blockinfile:
    dest: '{{ node_user_home }}/.bashrc'
    block: |
      export PATH="$PATH:{{ cosmovisor_home }}/current/bin"
    marker: '# {mark} ANSIBLE MANAGED BLOCK - CHAIN PATH'
    insertbefore: EOF
    create: true

- name: Add cosmovisor parmeters to .bashrc file for easy usage
  ansible.builtin.blockinfile:
    dest: "{{ node_user_home }}/.bashrc"
    block: |
      export DAEMON_NAME={{ chain_binary_name }}
      export DAEMON_HOME={{ chain_home }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK - COSMOVISOR CONFIG VAR"
    insertbefore: EOF
    create: true
