# get genesis.json file
- name: Fetch genesis.json file from url
  when: genesis_json_url is defined
  ansible.builtin.get_url:
    url: "{{ genesis_json_url }}"
    dest: "{{ chain_home }}/config/genesis.json"

- name: Enable prometeous
  ansible.builtin.lineinfile:
    path: "{{ chain_home }}/config/config.toml"
    regexp: '^prometheus = '
    line: prometheus = true

- name: Set up minimum-gas-price
  ansible.builtin.lineinfile:
    path: "{{ chain_home }}/config/app.toml"
    regexp: '^minimum-gas-prices = '
    line: minimum-gas-prices = "{{ minimum_gas_prices }}"

- name: Set moniker for node
  ansible.builtin.lineinfile:
    path: "{{ chain_home }}/config/config.toml"
    regexp: '^moniker = '
    line: moniker= "{{ chain_moniker }}"

- name: Set persistent peers
  ansible.builtin.lineinfile:
    path: "{{ chain_home }}/config/config.toml"
    regexp: '^persistent_peers = '
    line: persistent_peers = "{{ persistent_peers }}"

## TODO: Add rpc end point variable to the statesync script (currently set as a constant)
- name: Set statesync variables
  when: state_sync_disable is undefined
  ansible.builtin.script: state_sync.sh {{ snapshot_rpc }} {{ chain_home }}
