---
- name: Configure systemd service for cosmovisor
  when: use_cosmovisor
  ansible.builtin.template:
    src: cosmovisor.service.j2
    dest: "/etc/systemd/system/{{ cosmovisor_service_name }}.service"
    force: false

- name: Enable cosmovisor systemd service
  when: use_cosmovisor
  ansible.builtin.systemd:
    daemon_reload: true
    state: stopped
    enabled: true
    name: "{{ cosmovisor_service_name }}"

- name: Start cosmovisor systemd service
  when: use_cosmovisor
  ansible.builtin.systemd:
    daemon_reload: true
    state: restarted
    enabled: true
    name: "{{ cosmovisor_service_name }}"
  tags:
    - chain_start
    - chain_restart
